name: common_github_search
description: Shared Code between AngularDart and Flutter.
version: 1.0.0
repository: https://github.com/billy0402/flutter-github-search

environment:
  sdk: '>=2.16.2 <3.0.0'

# Add regular dependencies here.
dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  http: ^0.13.4
  stream_transform: ^2.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
