name: common_github_search
description: Shared Code between AngularDart and Flutter.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  http: ^0.13.4
  stream_transform: ^2.0.0

dev_dependencies:
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
