name: angular_github_search
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ngdart: ^8.0.0-dev.4
  angular_bloc: ^10.0.0-dev.2
  bloc: ^8.1.3
  common_github_search:
    path: ../common_github_search

dev_dependencies:
  build_daemon: ^4.0.1
  build_runner: ^2.4.8
  build_test: ^2.2.2
  build_web_compilers: ^4.0.9
  build_modules: ^5.0.7
  lints: ^3.0.0
  test: ^1.25.2
